### ISSUE TITLE
Generated filesnames from district courts contain "null"

### ISSUE THREAD

**Issue by tjohns** [freelawproject/recap-chrome#3]
When viewing PDF files from the AZ district court, the generated PDF filename contains "null" instead of a valid case number.

**Steps to reproduce:**
1. Visit: https://ecf.azd.uscourts.gov/doc1/02502127266
2. Click on "View Document".

**Actual results:**
Once the PDF file is displayed in Chrome, the blue buttons generated by RECAP in the upper-left read:
- Save as gov.uscourts.azd.null.null.0.pdf
- Save as D.Airz._null_null_0.pdf

**Expected results:**
An actual case ID should be used in the filename instead of "null".

**User-agent:**
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36

**Comment by divergentdave** [comment]
I got similar file download names in Chrome with the AZ district court. (i.e. gov.uscourts.azd.null.null.0.pdf) I got a different set of problems in Firefox, but that's a story for a different repo. (see freelawproject/recap-firefox#19) It looks like there's a common issue with parsing case numbers for this court.

**Comment by divergentdave** [comment]
It looks like the problem here is at least partly the same as with the Firefox extension. `PACER.getCaseNumberFromUrl()` is supposed to pull the PACER number of a case from the query string of the current URL or the query string of the referrer. Due to changes in PACER itself, there is no longer an interstitial page before you get a docket report, so the PACER number is never in the query string of any page. The fix here will probably be along the same lines as in freelawproject/recap-firefox#19, getting the case_num when the request is sent for a docket report, and then reusing that when we get the report back.

This brings up another question, didn't RECAP used to offer you a cached docket report when you were at the interstitial page before paying PACER for the docket? Should RECAP do the same thing on the form beforehand? There's an AJAX button you click after entering a case citation -- we could send our own AJAX request off to RECAP once the first AJAX request comes back with the PACER case number, see if a cached docket is available, and then add UI offering it to the user.

**Comment by mlissner** [comment]
> This brings up another question, didn't RECAP used to offer you a cached docket report when you were at the interstitial page before paying PACER for the docket? Should RECAP do the same thing on the form beforehand? There's an AJAX button you click after entering a case citation -- we could send our own AJAX request off to RECAP once the first AJAX request comes back with the PACER case number, see if a cached docket is available, and then add UI offering it to the user.

I don't think I've ever seen this functionality in RECAP, but if we want to add it, we should probably spin that off to another ticket.
